export const typeDefs = `#graphql
    type DichVu {
        tenDichVu: String,
        maDichVu: String,
        moTaDichVu: String,
        gia: Int,
        thoiGian: Int,
        icon: String,
        iconSelected: String,
    },
    type DiaChi {
        tinh: String,
        huyen: String,
        xa: String,
        soNhaTenDuong: String
    },
    type NhanVien {
        tenNhanVien: String,
        gioiTinh: String,
        ngaySinh: String,
        diaChi: String,
        soDienThoai: String,
        email: String,
        cccd: String,
        dichVu: [String],
        ghiChu: String,
        trangThaiTaiKhoan: String,
        danhGia: Float,
        trangThaiHienTai: String,
        lichLamViec: [LichThucHien]
    },
    type KhachHang {
        tenKhachHang: String,
        danhSachDiaChi: [String],
        soDienThoai: String,
        email: String
    },
    type LichThucHien {
        thoiGianBatDauLich: Int,
        thoiGianKetThucLich: Int,
        trangThaiLich: String
    },
    type DonHang {
        maDonHang:  String,
        ngayDatHang: String,
        ngayBatDau: String,
        ngayKetThuc: String,
        soGioThucHien: Int,
        trangThaiDonHang: String,
        danhSachLichThucHien: [LichThucHien],
        khachHang: KhachHang,
        nhanVien: NhanVien,
        danhSachDichVu: [DichVu],
        vatNuoi: String,
        ghiCHu: String,
        saoDanhGia: String,
        ghiChuDanhGia: String,
    },
    type Query {
        DiaChis: [DiaChi],
        DichVus: [DichVu],
        DonHangs: [DonHang],
        KhachHangs: [KhachHang],
        LichThucHiens: [LichThucHien],
        NhanViens: [NhanVien],
        DichVuCaLe: [DichVu],
        DonHangTheoId(idDonHang: String): DonHang
        DichVuThem: [DichVu],
        DanhSachNhanVienTrongViec(idDonHang: String): [NhanVien],
    },
    type Mutation {
        themDichVu(tenDichVu: String!, maDichVu: String, moTaDichVu: String, gia: Int, thoiGian: Int, icon: String, iconSelected: String): DichVu,
        themDonHang(
            maDonHang:  String,
            ngayDatHang: String,
            ngayBatDau: String,
            ngayKetThuc: String,
            soGioThucHien: Int,
            danhSachLichThucHien: [String],
            khachHang: String,
            nhanVien: String,
            danhSachDichVu: [String],
            vatNuoi: String,
            ghiCHu: String,
            saoDanhGia: String,
            trangThaiDonHang: String,
            ghiChuDanhGia: String): DonHang,
        themKhachHang(tenKhachHang: String, danhSachDiaChi: [String], soDienThoai: String, email: String): KhachHang,
        themNhanVien(
            tenNhanVien: String, 
            gioiTinh: String, 
            ngaySinh: String, 
            diaChi: String, 
            soDienThoai: String, 
            email: String, 
            cccd: String, 
            dichVu: [String], 
            ghiChu: String, 
            trangThaiTaiKhoan: String, 
            danhGia: Float, 
            lichLamViec: [String],
            trangThaiHienTai: String): NhanVien,
        themLichThucHien(thoiGianBatDauLich: Int, thoiGianKetThucLich: Int, trangThaiLich: String): LichThucHien,
    }
`